export const Centers = [
  {
    Name: "Hermita Guayabo",
    Provincia: "Guanacaste",
    Canton: "Bagaces",
    Distrito: "Mogote",
    Numero: "26731105",
    Email: "hermita@miravalles.net",
    Schecudale: "Lunes a viernes 8am a 12pm",
    UserAdmin: 8,
    Enabled: true,
  },
  {
    Name: "Rancho Español",
    Provincia: "Alajuela",
    Canton: "Alajuela",
    Distrito: "Guacima",
    Numero: "24380071",
    Email: "crisol@guacimacountryinn.net",
    Schecudale: "Lunes  3pm a 12am",
    UserAdmin: 9,
    Enabled: true,
  },
  {
    Name: "Tipico Copey",
    Provincia: "Heredia",
    Canton: "Santa Barbara",
    Distrito: "San Pedro",
    Numero: "22557489",
    Email: "copey@sanpedro.net",
    Schecudale: "Lunes a vierner 24/7",
    UserAdmin: 10,
    Enabled: true,
  },
];

