const Materials = [
  {
    Name: "Cobre",
    Description: "Material Conductor de energia",
    Image: null,
    Color: "#FF6347",
    Unit: "kg",
    Price: "10",
  },
  {
    Name: "Plomo",
    Description: "Material toxico usado para fijacion",
    Image: null,
    Color: "#4682B4",
    Unit: "kg",
    Price: "20",
  },
  ,
  {
    Name: "Carton",
    Description: "Material basado en metal comprimido",
    Image: null,
    Color: "#A52A2A",
    Unit: "L",
    Price: "20",
  },
  {
    Name: "Papel",
    Description: "Papel listo paraa reciclar",
    Image: null,
    Color: "#FFD700",
    Unit: "L",
    Price: "20",
  },
  {
    Name: "Botellas plasticas",
    Description: "Botellas listas para reciclar",
    Image: null,
    Color: "#87CEEB",
    Unit: "kg",
    Price: "20",
  },
  {
    Name: "Goma de poliuretano",
    Description: "Listo para crear formados",
    Image: null,
    Color: "#B0E0E60",
    Unit: "L",
    Price: "20",
  },
  {
    Name: "Aserrin",
    Description: "Listo para comprimir",
    Image: null,
    Color: "#6D5843",
    Unit: "kg",
    Price: "20",
  },
  {
    Name: "Comida",
    Description: "Restos de comida listo para compostaje",
    Image: null,
    Color: "#32CD32",
    Unit: "kg",
    Price: "20",
  }
];
